name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        run: |
          az deployment group create \
            --resource-group community-research \
            --template-file infra/main.bicep \
            --parameters location=westus2
