name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 86772acf-2f10-4aa8-ac3c-1d79d4a24e64
          resourceGroupName: community-research
          template: ./infra/main.bicep
          parameters: location=westus2
          deploymentName: commhub-deploy

