name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade Azure CLI
        run: az upgrade --yes || true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (direct REST API, safe JSON injection)
        shell: bash
        run: |
          echo "Building Bicep into JSON template..."
          az bicep build --file infra/main.bicep --outfile infra/main.json

          echo "Creating wrapped deployment payload..."
          # base64-encode the compiled template to avoid jq parsing issues
          TEMPLATE_B64=$(base64 -w0 infra/main.json)

          # Construct deployment body JSON safely
          cat > infra/deployment-final.json <<EOF
          {
            "properties": {
              "mode": "Incremental",
              "template": $(echo "$TEMPLATE_B64" | base64 --decode),
              "parameters": {
                "location": { "value": "westus2" }
              }
            }
          }
          EOF

          echo "Submitting deployment directly to ARM REST API..."
          az rest \
            --method put \
            --uri "https://management.azure.com/subscriptions/86772acf-2f10-4aa8-ac3c-1d79d4a24e64/resourcegroups/community-research/providers/Microsoft.Resources/deployments/commhub-deploy?api-version=2022-09-01" \
            --body @"infra/deployment-final.json" \
            --headers "Content-Type=application/json"

          echo "Deployment request submitted. Checking status..."
          az deployment group show \
            --resource-group community-research \
            --name commhub-deploy \
            --query "properties.provisioningState"

      - name: Verify resources
        run: az resource list -g community-research -o table
